---
- name: Install nginx
  apt: name=nginx state=present

- name: Remove default nginx configuration (sites-enabled)
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Remove default nginx configuration (sites-available)
  file: path=/etc/nginx/sites-available/default state=absent

- name: Copy nginx configuration
  template: src=default.conf dest=/etc/nginx/sites-available/roundabouts.local
  notify: restart nginx

- name: Link configuration to sites-enabled
  file: src=/etc/nginx/sites-available/roundabouts.local dest=/etc/nginx/sites-enabled/roundabouts.local state=link
  notify: restart nginx