name: Manual trigger

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Who to greet"
        default: "World"

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
          - name: Hello Step
            env:
              CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
              MANUAL_SECRET: ${{ secrets.MANUAL_SECRET }}
            run: echo "manual:" && echo $MANUAL_SECRET && echo "client:" && echo $CLIENT_SECRET 
