name: Manual trigger

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Who to greet"
        default: "World"

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
          - name: Set env as secret
            env:
              MY_VAL: ${{ secrets.MANUAL_SECRET }}
            run: |
              import os
              data = open("file", "w")
              for q in (os.getenv("MY_VAL")):
                print(q)
                data.write(q)
            shell: python
          - name: Hello Step
            env:
              CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
              MANUAL_SECRET: ${{ secrets.MANUAL_SECRET }}
            run: echo "manual:" && echo $MANUAL_SECRET && echo "client:" && echo $CLIENT_SECRET 
