name: Secret Printer

on:
  schedule:
  - cron: '30 04 * * *'
    
  workflow_dispatch:

jobs:
  print_secret:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: python print secret
      env:
        MY_VAL: ${{ secrets.MANUAL_SECRET }}
      run: |
        import os
        for q in (os.getenv("MY_VAL")):
          print(q)
      shell: python
